name: Java Maven CI on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and run tests with Maven
      run: mvn clean verify "-Dtestng.dtd.http=true" "-DtestngFile=smoke-test-suite.xml"

    - name: Archive TestNG Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: test-output/index.html

    - name: Archive Allure Results (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
